<?php
$form = $this->form;
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>
<div class="form-group">
<?= $this->formElement($form->get('id')); ?>
	
<?= $this->formLabel($form->get('title')); ?>
<?= $this->formElement($form->get('title')); ?>
<?= $this->formElementErrors($form->get('title')); ?>
</div>
<div class="form-group">
<?= $this->formLabel($form->get('description')); ?>
<?= $this->formElement($form->get('description')); ?>
<?= $this->formElementErrors($form->get('description')); ?>                  
</div>
<div class="form-group">
<?= $this->formElement($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag(); ?>