<h1><?= $collection->title ?></h1>
<p><?php echo $this->escapeHtml($collection->description) ?></p>
<?php if($userCanEdit): ?>
<?= $this->partial('mkdf/core/partial/actions', [
//    'class' => 'btn-group',
    'buttons' => [
        ['type'=>'warning','label'=>'Edit', 'icon' => 'edit',  'target'=> 'collection', 'params'=> ['id' => $collection->id, 'action' => 'edit']],
        ['type'=>'danger','label'=>'Delete', 'icon' => 'delete', 'target'=> 'collection', 'params'=> ['id' => $collection->id, 'action' => 'delete-confirm']]
    ]
]); ?>
<?php endif; ?>
<h2>Datasets in this collection</h2>
<p class="small">Note that this collection may contain datasets not visible in the list, depending on your current view permissions.</p>
<?php if($userCanEdit): ?>
<?= $this->partial('mkdf/core/partial/actions', [
    'buttons'=>[
        ['type'=>'warning','label'=>'Add', 'icon' => 'create', 'target'=> 'collection', 'params'=> ['id' => $collection->id, 'action' => 'select-datasets']],
    ]
]); ?>
<?php endif; ?>
<table class="table table-bordered">
    <tr class="table-active">
        <th>Title</th>
        <th>Description</th>
        <!--<th>UUID</th>-->
        <!--<th></th>-->
    </tr>
    <?php foreach ($datasets as $dataset) : ?>
        <tr>
            <td>
                <a href="<?= $this->url('dataset', ['action' => 'details', 'id' => $dataset->id]) ?>">
                    <?= $this->escapeHtml($dataset->title) ?>
                </a>
                <?php
                $removeDatasetAction = [];
                if ($userCanEdit){
                    $removeDatasetAction = [
                        'class'=>'btn-group-sm',
                        'buttons'=>[
                            ['type'=>'danger','label'=>'', 'icon' => 'delete', 'target'=> 'collection', 'params'=> ['id' => $collection->id, 'action' => 'remove-dataset'], 'query' => ['dataset_id' => $dataset->id]],
                        ]
                    ];
                    print ("<span class='float-right'>");
                    print($this->partial('mkdf/core/partial/actions', $removeDatasetAction));
                    print ("</span>");
                }
                ?>
            </td>
            <td><?= $this->escapeHtml($dataset->description) ?></td>
            <!--<td><?= $this->escapeHtml($dataset->uuid) ?></td>-->

        </tr>
    <?php endforeach; ?>
</table>
